name: Portfolio
on:
  push:
      branches: [main]
permissions:
      pages: write
      id-token: write
jobs:
    deploy:
        runs-on: ubuntu-latest
        environments: 
            name: github-pages
            url: ${{ steps.deployment.outputs.url}}
        steps:
        # get access to your portfolio code via pre-built action
            - name: Checkout Code
              uses: actions/checkout@v4
        # setup github pages 
            - name: Setup github pages
              uses: actions/configure-pages@v4

         # static pages 
            - name: uplad static files
              uses: actions/upload-pages-artifact2v4
          # page live
            - name: delpoy to github pages
              uses: action/deploy-pages@v4
  
      
              
